import fs from 'fs';
import path from 'path';
import { log } from './helpers.js';

/**
 * Export cookies from Puppeteer page to Netscape cookies.txt format
 * This file can be used by yt-dlp with --cookies flag
 * 
 * Netscape format:
 * domain\tTRUE/FALSE\tpath\tTRUE/FALSE\texpiry\tname\tvalue
 */
export async function exportCookies(page, outputPath) {
  log('🍪 Exporting cookies from browser session...');

  const cookies = await page.cookies('https://www.instagram.com');

  if (!cookies || cookies.length === 0) {
    log('⚠️ No cookies found! Make sure you are logged in.');
    return false;
  }

  // Build Netscape cookies.txt format
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by Instagram Reels Scraper',
    '# https://curl.haxx.se/docs/http-cookies.html',
    '',
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expires ? Math.floor(cookie.expires) : 0;

    lines.push(
      `${domain}\t${includeSubdomains}\t${cookie.path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`
    );
  }

  // Ensure output directory exists
  const dir = path.dirname(outputPath);
  if (dir && !fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
  log(`✅ Exported ${cookies.length} cookies to ${outputPath}`);

  // Verify sessionid is present
  const hasSession = cookies.some(c => c.name === 'sessionid');
  if (hasSession) {
    log('✅ Session cookie (sessionid) found — yt-dlp should work!');
  } else {
    log('⚠️ Warning: sessionid cookie not found. yt-dlp might not be able to access some content.');
  }

  return true;
}
